services:
  - type: worker
    name: youtube-downloader-bot
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: MAX_FILE_SIZE_MB
        value: "2000"
    autoDeploy: true
